version: '3.7'
services:
  me:
    container_name: me
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - /home/ubuntu/me/www:/usr/share/nginx/html
      - /home/ubuntu/me/www/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared_network

networks:
  shared_network:
    external: true